[workspace]
authors = ["Daniel Esteban Palma Igor <daniel.palma.i@ug.uchile.cl>"]
channels = ["conda-forge", "bioconda"]
name = "CAMISIM"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.7.*"
biopython = ">=1.79,<2"
biom-format = ">=2.1.12,<3"
numpy = ">=1.21.6,<2"
matplotlib = ">=3.5.3,<4"
perl-xml-simple = ">=2.25,<3"
samtools = ">=1.18,<2"
joblib = ">=1.3.2,<2"
scikit-learn = ">=1.0.2,<2"
ete3 = ">=3.1.3,<4"
